[package]

name = "glob"
version = "0.3.0"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/rust-lang/glob"
repository = "https://github.com/rust-lang/glob"
documentation = "https://docs.rs/glob/0.3.0"
description = """
Support for matching file paths against Unix shell style patterns.
"""
categories = ["filesystem"]

[dev-dependencies]
tempdir = "0.3"
